### ISSUE TITLE
polymer tail entangled

### ISSUE THREAD

**Issue by hosseinv93** [nanogchen/polyGraft#2]
Hello,

Firstly, I'd like to express my gratitude for your excellent code. It's been very useful. I have a query regarding system preparation for nanopore brushes. I'm encountering a challenge where the polymers, being longer than the pore size, end up with their free ends severely entangled. This entanglement persists despite extended molecular dynamics (MD) simulations. Could you suggest a method to set up the systems in a more randomized manner? Specifically, I'm looking for a way to have the polymers' free ends distributed randomly within the pore to avoid this issue of entanglement.

**Comment by nanogchen** [comment]
Hi, thank you for your interest!

The problem with nanopore brush is that the available space away from the surface (or close to pore center) is much less than that near the surface, unlike convex or planar brush. One way to generate the nanopore brush is using a curved polymer for the grafts (like a damped sinusoidal wave) to make use of the space near the surface, shown below:

![image](https://github.com/nanogchen/polyGraft/assets/90920704/871feea7-376b-4808-9fbd-2fadb6d541b7)

If the grafting density is not high, it is feasible. However it becomes increasingly difficult to generate nanopore brush if the graft is too long (than the radius of the pore) and the grafting density is high.

Using a randomized orientation of the polymer for nanopore brush does not fully solve the problem, as they might still entangle, if not controlled in a well-defined way. 

PS: Avogadro can be used to generate polymer with desired conformation (use energy minimization and pull atoms with an end atom fixed).

**Comment by nanogchen** [comment]
Update: one way to get around the space limit is to use the axial space along the nanopore (shown below, thanks to Chris), then one can relax the polymer before use it for production run. 

![Pore](https://github.com/nanogchen/polyGraft/assets/90920704/7a56b982-eaff-4522-864a-86eee190196f)
